### ISSUE TITLE
[Server] [5h] : 유저정보암호화 

### ISSUE THREAD

**Issue by Candyroom136** [codestates/codestory2.0#12]
### ISSUE
- Group:  서버
- Type:  기능보완
- Detail: 유저 정보를 암호화 하여 저장

### TODO
1. [ ] salt와 hash function이용하여 유저 비밀번호를 암호화
2. [ ] 데이터에베이스에 암호화된 유저 비밀번호와 salt를 저장
3. [ ] 유저 로그인시 유저가 입력한 비밀번호와 데이터베이스에 저장된 salt를 입력하여 암호화 한후 데이터베이스 비밀번호와 비교.

### Estimated time
> Pick one
