### ISSUE TITLE
[Server] [2h] : 데이터베이스 테이블 구성  

### ISSUE THREAD

**Issue by Candyroom136** [codestates/codestory2.0#190]
### ISSUE
- Group:  서버
- Type:  기능보완
- Detail: 데이터베이스 테이블을 db schema를 따라 구성

### TODO
1. [ ] 데이터베이스 테이블을 migration:undo를 통해 초기화 한다.
2. [ ] 초기화 한 시점 이후 migration파일을 삭제한 후 새롭게 추가할 칼럼들과 관련된 migration파일을 만든다.
3. [ ] migration을 작동시켜 새롭게 table을 구성한다.
