### ISSUE TITLE
[Server] [2h] : 데이터 연결 작동방식 속도 실험 

### ISSUE THREAD

**Issue by Candyroom136** [codestates/codestory2.0#191]
### ISSUE
- Group:  서버
- Type:  기타
- Detail: 클라이언트에서 데이터를 얻어오는 방식들의 통신 속도를 비교하여 제일 좋은 방식을 알아낸다.

### TODO
1. [ ] signin component에서 현재 api를 이용한 방식을 사용할 때의 반응속도를 측정한다.
2. [ ] signin component에서 api가 아닌 signin이 있는 페이지에서 ssr방식으로 데이터를 얻어올때의 반응속도를 측정한다.
3. [ ] signin component가 있는 곳에서 데이터베이스를 연결 할 수 있는지 확인 후 있다면 반응속도를 측정한다.
4. [ ] 앞서 구한 측정속도를 비교하여 가장 좋은 통신방법을 도출한다.
