### ISSUE TITLE
[Client] [3h] : 랭킹 컴포넌트 api 연결

### ISSUE THREAD

**Issue by seoyong-lee** [codestates/codestory2.0#195]
### ISSUE
- Group:  클라이언트
- Type:  기능추가
- Detail: 랭킹 컴포넌트 api 연결 및 팔로우 관련 기능 추가

### TODO
1. [x] 랭킹 api 연결
2. [x] 팔로우 기능 추가
3. [x] 팔로우 api 연결
