### ISSUE TITLE
[Client] [3h] : 프로필 api 연결

### ISSUE THREAD

**Issue by seoyong-lee** [codestates/codestory2.0#196]
### ISSUE
- Group:  클라이언트
- Type:  기능추가
- Detail: 프로필 api 연결

### TODO
1. [x] 랭킹 아이디 및 스코어 api 연결
2. [ ] 사진 업로드 api 연결
3. [ ] 나의 한마디 업로드 api 연결
