### ISSUE TITLE
[Client] [3h] : Linux game font 수정과 view 수정 

### ISSUE THREAD

**Issue by satoshi25** [codestates/codestory2.0#222]
### ISSUE
- Group:  클라이언트
- Type:  기능보완
- Detail: Linux game font 수정과 view 수정 

### TODO
1. [x] Linux game font 수정
2. [x] font view 수정 
3. [x] font 반응형 수정
