### ISSUE TITLE
[Server] [4h] : 게임 파일 불러오는 방식 변경 

### ISSUE THREAD

**Issue by Candyroom136** [codestates/codestory2.0#233]
### ISSUE
- Group: 서버
- Type:  기능보완
- Detail: 게임 파일을 static file serving하여 fetch해오는 방식에서 빌드때부터 fs module을 이용하여 데이터를 불러오는 방식으로 변경하여 로딩속도증가

### TODO
1. [ ] getStaticProps안에서 fs, process.cwd를 이용하여 파일내용을 불러와 props에 담기
2. [ ] 파일내용을 담은 props를 게임컴포넌트까지 내려주기
3. [ ] 필요없는 public/games, 게임 api삭제

### Estimated time
> Pick one
